version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: parcial-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - app_net

  api:
    build: .
    container_name: parcial-api
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      PORT: "${PORT}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      ESTUDIANTE_NOMBRE: "${ESTUDIANTE_NOMBRE}"
      ESTUDIANTE_EXPEDIENTE: "${ESTUDIANTE_EXPEDIENTE}"
      ESTUDIANTE_CODIGO: "${ESTUDIANTE_CODIGO}"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_net

volumes:
  db_data:
    external: true   # usamos el volumen nombrado creado antes

networks:
  app_net:
    driver: bridge
